name: Python package

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install cookiecutter pytest tox pytest-cov
    - name: test
      run: |
        pytest --cov {{cookiecutter.project_slug}} --cov-report html --cov-report xml:coverage.xml
    - name: Run coverage
      run: |
        coverage report
        coverage xml
    - uses: codecov/codecov-action@v1        
