name: Python package

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install cookiecutter pytest
    - name: test
      run: |
        cookiecutter . --no-input
        cd ./python_boilerplate && pytest -vv
